"""
Sample the hull's cross-sections into the table the water shader clips against.

The app's sea cuts a hull-shaped hole in the water so waves do not render
inside the cabin. That cut is tested in the hull's own frame, in 3-D: half-beam
by (station, height), because the hull tucks inward below the waterline and
flares above it, and the wave surface meets it at a different height every
frame. This script measures that table off the built mesh and writes it to
`src/scene/water/hullSections.ts` as generated, committed source.

Run it after any change to the hull's shape:

    flatpak run org.blender.Blender -b --factory-startup \
        --python "$PWD/blender/tools/hull_sections.py" -- --project "$PWD"

Bins hold the max |x| of hull vertices falling in them, mirrored across the
centreline (the hull is symmetric; sampling |x| uses both halves). Empty bins
are 0, which the shader reads as "no hull here, keep the water" -- that is what
puts sea under the bow and stern overhangs in a trough.

Axes: the .blend is Blender-space (+Y bow, Z up, waterline at z=0). The app is
three.js-space via the glTF exporter (x -> x, z -> y, -y -> z), so a Blender
(y, z) bin becomes a three.js (-z, y) bin. The table is written in three.js
terms -- station axis is world z from stern (+) to bow (-) -- so the app never
needs to know Blender existed.
"""

import os
import sys

import bpy

STATIONS = 64
HEIGHTS = 32
HEIGHT_MIN = -0.70
HEIGHT_MAX = 0.70
"""Vertical band the table covers, metres about the waterline. Wider than any
wave excursion the scene can produce (amplitudes sum to ~0.4, plus pitch at the
ends), so the shader never samples off the table's edge in normal running."""


def parse_args(argv):
    args = argv[argv.index("--") + 1 :] if "--" in argv else []
    out = {"project": os.getcwd()}
    for i, token in enumerate(args):
        if token == "--project" and i + 1 < len(args):
            out["project"] = os.path.abspath(args[i + 1])
    return out


def main():
    opts = parse_args(sys.argv)
    project = opts["project"]

    blend = os.path.join(project, "blender", "maxi77.blend")
    out_path = os.path.join(project, "src", "scene", "water", "hullSections.ts")

    bpy.ops.wm.open_mainfile(filepath=blend)
    hull = bpy.data.objects["hull"]
    verts = [hull.matrix_world @ v.co for v in hull.data.vertices]

    in_band = [v for v in verts if HEIGHT_MIN <= v.z <= HEIGHT_MAX]
    y_min = min(v.y for v in in_band)
    y_max = max(v.y for v in in_band)

    # Bin max |x| by (station, height). Station bins run Blender y ascending;
    # heights run bottom to top.
    table = [[0.0] * STATIONS for _ in range(HEIGHTS)]
    y_span = y_max - y_min
    z_span = HEIGHT_MAX - HEIGHT_MIN
    for v in in_band:
        si = min(STATIONS - 1, int((v.y - y_min) / y_span * STATIONS))
        hi = min(HEIGHTS - 1, int((v.z - HEIGHT_MIN) / z_span * HEIGHTS))
        table[hi][si] = max(table[hi][si], abs(v.x))

    # The loft is 96 stations over the whole hull, so at this resolution a bin
    # can fall between vertex rows and read empty inside the hull. Fill such
    # holes from their along-hull neighbours -- but never grow the ends: a zero
    # beyond the last occupied station is the overhang, and it must stay zero.
    for hi in range(HEIGHTS):
        row = table[hi]
        occupied = [i for i, v in enumerate(row) if v > 0.0]
        if not occupied:
            continue
        first, last = occupied[0], occupied[-1]
        for i in range(first, last + 1):
            if row[i] == 0.0:
                prev_i = max(j for j in occupied if j < i)
                next_i = min(j for j in occupied if j > i)
                t = (i - prev_i) / (next_i - prev_i)
                row[i] = row[prev_i] * (1 - t) + row[next_i] * t

    # Flatten in three.js orientation: station axis from stern to bow means
    # walking Blender y *ascending* (stern y_min -> bow y_max) equals three z
    # *descending* -- so emit stations in Blender order and record the z range
    # as (stern_z, bow_z) = (-y_min, -y_max).
    flat = []
    for hi in range(HEIGHTS):
        flat.extend(table[hi])

    lines = []
    lines.append("/**")
    lines.append(" * GENERATED by blender/tools/hull_sections.py -- do not edit by hand.")
    lines.append(" * Regenerate after any change to the hull's shape:")
    lines.append(" *")
    lines.append(" *     flatpak run org.blender.Blender -b --factory-startup \\")
    lines.append(' *         --python "$PWD/blender/tools/hull_sections.py" -- --project "$PWD"')
    lines.append(" *")
    lines.append(" * Hull half-beam in metres by (station, height): STATIONS columns from")
    lines.append(" * stern to bow, HEIGHTS rows from the bottom of the band up. 0 means no")
    lines.append(" * hull at that spot (an overhang, or below the canoe body) and the sea")
    lines.append(" * shader keeps the water there.")
    lines.append(" */")
    lines.append(f"export const SECTION_STATIONS = {STATIONS}")
    lines.append(f"export const SECTION_HEIGHTS = {HEIGHTS}")
    lines.append(f"export const SECTION_STERN_Z = {-y_min:.3f}")
    lines.append(f"export const SECTION_BOW_Z = {-y_max:.3f}")
    lines.append(f"export const SECTION_HEIGHT_MIN = {HEIGHT_MIN}")
    lines.append(f"export const SECTION_HEIGHT_MAX = {HEIGHT_MAX}")
    lines.append("")
    lines.append("// prettier-ignore")
    lines.append("export const SECTION_HALF_BEAM = [")
    for hi in range(HEIGHTS):
        row = ", ".join(f"{v:.3f}" for v in table[hi])
        lines.append(f"  {row},")
    lines.append("]")
    lines.append("")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"[hull_sections] wrote {out_path}")
    print(f"[hull_sections] stations {STATIONS} ({y_min:.3f}..{y_max:.3f} Blender y)")
    print(f"[hull_sections] heights  {HEIGHTS} ({HEIGHT_MIN}..{HEIGHT_MAX})")


if __name__ == "__main__":
    main()
